---
timezone: America/Halifax
gems:
  - jekyll-archives

jekyll-archives:
  enabled:
  - year
  layout: 'archive'
  permalinks:
    year: '/posts/:year/'

collections:
  projects:
    output: true
    permalink: "/projects/:path/"
  jobs:
    output: true
    permalink: "/about/jobs/:path/"
  people:
    output: true
    permalink: "/about/people/:path/"
  publications:
    output: true
    permalink: "/publications/:path/"
  posts:
    output: true
    permalink: "/posts/:year/:title/"
exclude:
- node_modules
- gulpfile.js
- package.json
- vendor
show_drafts: false
highlighter: rouge
port: 4000
url: "https://chcresearch.ca"
permalink: "/:year/:title/"
timezone:
defaults:
- scope:
    path: ''
    type: ''
  values:
    sub-title: ''
- scope:
    path: ''
    type: 'posts'
  values:
    tags:
    - something
- scope:
    path: ''
    type: projects
  values:
    description: ''
    thumbnail: ''
    sub-title: ''
    tags: []
    slug: ''
- scope:
    path: ''
    type: publications
  values:
    project:
    - jekyll
    - update
    layout: text
    author: ''
    link: ''
    PDF: ''
- scope:
    path: ''
    type: jobs
  values:
    link: ''
- scope:
    path: ''
    type: people
  values:
    layout: person
    sub-title: ''
    thumbnail: ''
    tags (staff, board, advisor, partner): []
    email: ''
    linkedin: ''
kramdown:
  auto_ids: true
  toc_levels: 1..6
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: '1'
name: Belkirk College of Engineering and Design
footer-nav-about:
- title: About Us
  href: "/about"
- title: Staff
  href: "/about/staff"
- title: Board
  href: "/about/board"
- title: SPORE/MSSU
  href: "/about/spore-mssu"
- title: Partners Collaborators
  href: "/about/partners-collaborators"
- title: Job Postings
  href: "/about/jobs"
- title: Blog
  href: "/posts"
navigation:
- root: Home
  url: "/"
- root: About Us
  url: "/about"
  first-level:
  - text: About Us
    url: "/about"
  - text: Staff
    url: "/about/staff"
  - text: Board
    url: "/about/board"
  - text: SPOR/MSSU
    url: "/about/spore-mssu"
  - text: Partners Collaborators
    url: "/about/partners-collaborators"
  - text: Job Postings
    url: "/about/jobs"
- root: Projects
  url: "/projects"
- root: Publications
  url: "/publications"
- root: Contact Us
  url: "/contact"
