---
upload_path: "/uploads/"
frontmatter_file_url_template: "/uploads/"
body_file_url_template: "/uploads/"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections:
  _posts:
    default_front_matter_template: posts
  _projects:
    default_front_matter_template: projects
  _people:
    default_front_matter_template: people
  _publications:
    default_front_matter_template: publications
