---
upload_path: assets/images/
frontmatter_file_url_template: assets/images/
body_file_url_template: assets/images/
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
collections: {}
